Fixing the yml pipeline

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -77,13 +77,28 @@ jobs:
     needs: generate-report
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout repository
+      - name: Checkout gh-pages branch
         uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          ref: gh-pages
 
       - name: Download Allure report
         uses: actions/download-artifact@v4
         with:
           name: allure-report
+
+      - name: Debug Artifact Download
+        run: |
+          echo "Listing downloaded artifact contents:"
+          ls -l allure-report
+
+      - name: Check for Allure Report
+        run: |
+          if [ ! -d "allure-report" ]; then
+            echo "Allure report directory is missing!"
+            exit 1
+          fi
 
       - name: Set unique path for report
         run: |
